sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

language: cpp

compiler:
  - gcc

before_install:
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.sh
  - sudo sh cmake-3.3.1-Linux-x86_64.sh --skip-license --prefix=/usr
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

before_script:
  - mkdir build
  - cd build

script: cmake .. && make