sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

language: cpp

compiler:
  - gcc

before_install:
  - wget http://www.cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.sh
  - chmod +x cmake-3.6.3-Linux-x86_64.sh
  - sudo ./cmake-3.6.3-Linux-x86_64.sh --skip-license --prefix=/usr
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

before_script:
  - mkdir build
  - cd build

script: cmake .. && make
